Use parseInt and toString instead of lookup tables
pwlmc/imghash pull request #155
Opened 2021-10-17 22:23 UTC by timhuff

2021-11-01 16:20 UTC, pwlmaciejewski requested changes

2021-11-01 16:20 UTC, pwlmaciejewski commented on index.js
> +  return s.split('').map(hexDigit => parseInt(hexDigit, 16).toString(2)).join('')
@timhuff please fix the failing build

2022-11-04 22:27 UTC, Eghizio commented
This `hexToBinary` change breaks the tests

2022-11-06 19:06 UTC, timhuff commented
@pwlmaciejewski @Eghizio Pardon the delay on this. I'll get this fixed in a jiffy.

2025-07-19 10:12 UTC, closed without merging